In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
import urllib.parse

In [2]:
engine = ("postgresql://postgres:1503@localhost:5432/projects")
print("connected successfully")

connected successfully

In [3]:
query = """
SELECT 
    c.CustomerId, c.Surname, c.Geography, c.Gender, c.Age, c.CreditScore, c.EstimatedSalary,
    a.Tenure, a.Balance, a.NumOfProducts, a.HasCrCard, a.IsActiveMember, a.Exited
FROM bank_churn.customer_info c
INNER JOIN bank_churn.account_info a 
ON c.CustomerId = a.CustomerId;
"""
df = pd.read_sql(query,engine)
df.head()

,customerid,surname,geography,gender,age,creditscore,estimatedsalary,tenure,balance,numofproducts,hascrcard,isactivemember,exited
0,15647311,Hill,Spain,Female,41.0,608,"€ 112,542.58",1,"€ 83,807.86",1,Yes,Yes,0
1,15737888,Mitchell,Spain,Female,43.0,850,"€ 79,084.10",2,"€ 125,510.82",1,Yes,Yes,0
2,15574012,Chu,Spain,Male,44.0,645,"€ 149,756.71",8,"€ 113,755.78",2,No,No,1
3,15592531,Bartlett,France,Male,50.0,822,"€ 10,062.80",7,€ 0.00,2,Yes,Yes,0
4,15656148,Obinna,Germany,Female,29.0,376,"€ 119,346.88",4,"€ 115,046.74",4,No,No,1

In [4]:
df['estimatedsalary'] = df['estimatedsalary'].str.replace(',', '').str.replace('€', '').str.replace(' ','').astype(float)

In [5]:
df.head()

,customerid,surname,geography,gender,age,creditscore,estimatedsalary,tenure,balance,numofproducts,hascrcard,isactivemember,exited
0,15647311,Hill,Spain,Female,41.0,608,112542.58,1,"€ 83,807.86",1,Yes,Yes,0
1,15737888,Mitchell,Spain,Female,43.0,850,79084.10,2,"€ 125,510.82",1,Yes,Yes,0
2,15574012,Chu,Spain,Male,44.0,645,149756.71,8,"€ 113,755.78",2,No,No,1
3,15592531,Bartlett,France,Male,50.0,822,10062.80,7,€ 0.00,2,Yes,Yes,0
4,15656148,Obinna,Germany,Female,29.0,376,119346.88,4,"€ 115,046.74",4,No,No,1

In [6]:
df['balance'] = df['balance'].str.replace('€', '').str.replace(',','').astype(float)

In [7]:
df.head()

,customerid,surname,geography,gender,age,creditscore,estimatedsalary,tenure,balance,numofproducts,hascrcard,isactivemember,exited
0,15647311,Hill,Spain,Female,41.0,608,112542.58,1,83807.86,1,Yes,Yes,0
1,15737888,Mitchell,Spain,Female,43.0,850,79084.10,2,125510.82,1,Yes,Yes,0
2,15574012,Chu,Spain,Male,44.0,645,149756.71,8,113755.78,2,No,No,1
3,15592531,Bartlett,France,Male,50.0,822,10062.80,7,0.00,2,Yes,Yes,0
4,15656148,Obinna,Germany,Female,29.0,376,119346.88,4,115046.74,4,No,No,1

In [8]:
df["hascrcard"] = df["hascrcard"].map({'Yes' : 1, 'No' : 0})
df["isactivemember"] = df["isactivemember"].map({'Yes' : 1, 'No' : 0})

In [9]:
df.head()

,customerid,surname,geography,gender,age,creditscore,estimatedsalary,tenure,balance,numofproducts,hascrcard,isactivemember,exited
0,15647311,Hill,Spain,Female,41.0,608,112542.58,1,83807.86,1,1,1,0
1,15737888,Mitchell,Spain,Female,43.0,850,79084.10,2,125510.82,1,1,1,0
2,15574012,Chu,Spain,Male,44.0,645,149756.71,8,113755.78,2,0,0,1
3,15592531,Bartlett,France,Male,50.0,822,10062.80,7,0.00,2,1,1,0
4,15656148,Obinna,Germany,Female,29.0,376,119346.88,4,115046.74,4,0,0,1

In [10]:
df['customerid'].value_counts()[df['customerid'].value_counts() > 1]

customerid
15628319    4
15634602    2
Name: count, dtype: int64

In [11]:
df = df.drop_duplicates(subset=['customerid'], keep='first')

In [12]:
df['customerid'].duplicated().sum()

0

In [13]:
df['zero_balance'] = (df['balance'] == 0).astype(int)

In [14]:
df.head()

,customerid,surname,geography,gender,age,creditscore,estimatedsalary,tenure,balance,numofproducts,hascrcard,isactivemember,exited,zero_balance
0,15647311,Hill,Spain,Female,41.0,608,112542.58,1,83807.86,1,1,1,0,0
1,15737888,Mitchell,Spain,Female,43.0,850,79084.10,2,125510.82,1,1,1,0,0
2,15574012,Chu,Spain,Male,44.0,645,149756.71,8,113755.78,2,0,0,1,0
3,15592531,Bartlett,France,Male,50.0,822,10062.80,7,0.00,2,1,1,0,1
4,15656148,Obinna,Germany,Female,29.0,376,119346.88,4,115046.74,4,0,0,1,0

In [15]:
df = df.rename(columns={
    'customerid': 'customer_id',
    'surname': 'customer_name',
    'creditscore': 'credit_score',
    'geography': 'country',
    'gender': 'gender',
    'age': 'age',
    'estimatedsalary': 'estimated_salary',
    'tenure': 'tenure',
    'balance': 'balance',
    'numofproducts': 'total_products',
    'hascrcard': 'has_credit_card',
    'isactivemember': 'is_active',
    'exited': 'actual_churn'
})
print("Column names updated")
df.head(2)

Column names updated

,customer_id,customer_name,country,gender,age,credit_score,estimated_salary,tenure,balance,total_products,has_credit_card,is_active,actual_churn,zero_balance
0,15647311,Hill,Spain,Female,41.0,608,112542.58,1,83807.86,1,1,1,0,0
1,15737888,Mitchell,Spain,Female,43.0,850,79084.10,2,125510.82,1,1,1,0,0

In [16]:
numerical_cols = ['credit_score', 'age', 'tenure', 'balance', 'total_products', 'has_credit_card', 'is_active', 'estimated_salary','zero_balance']

for col in numerical_cols:
    if col in df.columns:
        # column ka average nikal kar khali jagah ko bhar dena
        df[col] = pd.to_numeric(df[col], errors='coerce')
        df[col] = df[col].fillna(df[col].median())

print("fill all messing values")
df.head(2)

fill all messing values

,customer_id,customer_name,country,gender,age,credit_score,estimated_salary,tenure,balance,total_products,has_credit_card,is_active,actual_churn,zero_balance
0,15647311,Hill,Spain,Female,41.0,608,112542.58,1,83807.86,1,1,1,0,0
1,15737888,Mitchell,Spain,Female,43.0,850,79084.10,2,125510.82,1,1,1,0,0

In [17]:
X = df.drop(columns=['customer_id', 'customer_name', 'actual_churn'])
y = df['actual_churn']

#numerical_cols = ['credit_score', 'age', 'tenure', 'balance', 'total_products', 'has_credit_card', 'is_active', 'estimated_salary', 'zero_balance']
categorical_cols = ['country', 'gender']


preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
    ])


X_processed = preprocessor.fit_transform(X)
print(" Preprocessing complete ")

 Preprocessing complete

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report


X_train, X_test, y_train, y_test = train_test_split(X_processed, y, test_size=0.2, random_state=42, stratify=y)

models = {
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(random_state=42)
}


model_accuracies = {}

print("⏳ All models are compare to each other..\n")


for name, model_obj in models.items():
    model_obj.fit(X_train, y_train)
    y_pred = model_obj.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    model_accuracies[name] = acc
    
    print(f"{name} Accuracy Score: {round(acc * 100, 2)}%")


best_model_name = max(model_accuracies, key=model_accuracies.get)
best_model = models[best_model_name]

print(f"\n FINAL MODEL: {best_model_name} (Accuracy: {round(model_accuracies[best_model_name]*100, 2)}%)")
print("Now, using this model, we will calculate the probability of the entire data\n")

best_model.fit(X_processed, y)

df['churn_probability'] = np.round(best_model.predict_proba(X_processed)[:, 1] * 100, 2)


def assign_risk_segment(prob):
    if prob >= 70: return 'High Risk'
    elif prob >= 40: return 'Medium Risk'
    else: return 'Low Risk'

df['risk_segment'] = df['churn_probability'].apply(assign_risk_segment)

print("🎯 AI/ML Pipeline Successfully Executed!")
df[['customer_name', 'churn_probability', 'risk_segment']].head()

⏳ All models are compare to each other..

Logistic Regression Accuracy Score: 80.2%
Decision Tree Accuracy Score: 77.85%
Random Forest Accuracy Score: 85.7%
Gradient Boosting Accuracy Score: 85.95%

 FINAL MODEL: Gradient Boosting (Accuracy: 85.95%)
Now, using this model, we will calculate the probability of the entire data

🎯 AI/ML Pipeline Successfully Executed!

  customer_name  churn_probability risk_segment
0          Hill              15.95     Low Risk
1      Mitchell              18.10     Low Risk
2           Chu              14.21     Low Risk
3      Bartlett               8.47     Low Risk
4        Obinna              96.95    High Risk

In [19]:
try:

    df.to_sql(
        name='final_bank_churn_predictions', 
        con=engine, 
        schema='bank_churn', 
        if_exists='replace', 
        index=False
    )
    print("All ML processed data saved to PostgreSQL bank_churn schema.")
    print("Table Name: bank_churn.final_bank_churn_predictions")
except Exception as e:
    print("Data not saved")
    print(e)

All ML processed data saved to PostgreSQL bank_churn schema.
Table Name: bank_churn.final_bank_churn_predictions